const { ROLES, ASSET_CATEGORIES, ASSET_STATUS, ASSET_CONDITION, LIFECYCLE_EVENTS } = require('../utils/constants');

const demoUsers = [
  {
    name: 'Dr. Rajeshwar Sharma, IAS',
    email: 'superadmin@infratrack.gov.in',
    password: 'Password@123',
    role: ROLES.SUPER_ADMIN,
    designation: 'Principal Secretary & State Chief Admin',
    employeeId: 'IAS-GJ-001',
    phone: '+91 98250 11001',
  },
  {
    name: 'Kavita Dave, CE',
    email: 'pwd.admin@infratrack.gov.in',
    password: 'Password@123',
    role: ROLES.DEPARTMENT_ADMIN,
    designation: 'Chief Engineer & Head of PWD',
    employeeId: 'PWD-CE-042',
    phone: '+91 98250 11002',
  },
  {
    name: 'Suresh Patel, SE',
    email: 'engineer.patel@infratrack.gov.in',
    password: 'Password@123',
    role: ROLES.ENGINEER,
    designation: 'Executive Engineer (Bridges & Roads)',
    employeeId: 'ENG-SRT-109',
    phone: '+91 98250 11003',
  },
  {
    name: 'Anjali Verma',
    email: 'inspector.sharma@infratrack.gov.in',
    password: 'Password@123',
    role: ROLES.INSPECTOR,
    designation: 'Senior Infrastructure Quality Inspector',
    employeeId: 'INSP-QC-215',
    phone: '+91 98250 11004',
  },
  {
    name: 'Vikram Mehta',
    email: 'finance.mehta@infratrack.gov.in',
    password: 'Password@123',
    role: ROLES.FINANCE_OFFICER,
    designation: 'Senior Accounts Officer (Capital Assets)',
    employeeId: 'FIN-AUD-301',
    phone: '+91 98250 11005',
  },
  {
    name: 'Mahesh Solanki',
    email: 'contractor.apex@infratrack.gov.in',
    password: 'Password@123',
    role: ROLES.CONTRACTOR,
    designation: 'Project Director (Apex Infra Ltd)',
    employeeId: 'CTR-APX-001',
    phone: '+91 98250 11006',
  },
  {
    name: 'Bhavna Desai, CAG',
    email: 'auditor.desai@infratrack.gov.in',
    password: 'Password@123',
    role: ROLES.AUDITOR,
    designation: 'State Public Accounts Auditor',
    employeeId: 'AUD-CAG-991',
    phone: '+91 98250 11007',
  },
];

const departmentsData = [
  {
    code: 'PWD',
    name: 'Public Works Department (Roads & Bridges)',
    description: 'State agency overseeing highways, urban arterials, flyovers, and public building infrastructure.',
    contactEmail: 'pwd.gujarat@infratrack.gov.in',
    contactPhone: '+91 261 2451000',
    state: 'Gujarat',
    district: 'Surat',
  },
  {
    code: 'WRD',
    name: 'Water Resources & Municipal Supply Board',
    description: 'Bulk water supply, treatment plants, distribution pipelines, and drainage networks.',
    contactEmail: 'water.surat@infratrack.gov.in',
    contactPhone: '+91 261 2452000',
    state: 'Gujarat',
    district: 'Surat',
  },
  {
    code: 'TRANS',
    name: 'Urban Transport & Smart Mobility Authority',
    description: 'BRTS corridors, traffic signaling, intelligent transit terminals, and multimodal hubs.',
    contactEmail: 'transport.surat@infratrack.gov.in',
    contactPhone: '+91 261 2453000',
    state: 'Gujarat',
    district: 'Surat',
  },
  {
    code: 'ENERGY',
    name: 'Energy & Renewable Power Development Board',
    description: 'Grid transformers, solar installations, urban street lighting, and smart microgrids.',
    contactEmail: 'energy.board@infratrack.gov.in',
    contactPhone: '+91 261 2454000',
    state: 'Gujarat',
    district: 'Surat',
  },
  {
    code: 'HEALTH',
    name: 'Health & Medical Infrastructure Corporation',
    description: 'Government hospitals, trauma centers, maternal care facilities, and urban health posts.',
    contactEmail: 'health.infra@infratrack.gov.in',
    contactPhone: '+91 261 2455000',
    state: 'Gujarat',
    district: 'Surat',
  },
];

const contractorsData = [
  {
    companyName: 'Apex Infrastructure & Civil Engineering Ltd',
    registrationNumber: 'GJ-PWD-CL1-2018-091',
    contactPerson: 'Mahesh Solanki',
    email: 'contractor.apex@infratrack.gov.in',
    phone: '+91 98250 11006',
    address: 'Plot 42, GIDC Pandesara Industrial Estate, Surat, Gujarat',
    specializations: ['Bridges', 'Highways', 'Flyovers', 'Prestressed Concrete'],
    licenseValidUntil: new Date('2028-12-31'),
    rating: 4.8,
  },
  {
    companyName: 'Gujarat Urban Utility & Power Solutions Ltd',
    registrationNumber: 'GJ-ENG-CL1-2020-142',
    contactPerson: 'Nitin Bhatt',
    email: 'contact@gujaratpowertech.in',
    phone: '+91 98250 22001',
    address: 'Electronic Estate, Sector 25, Gandhinagar, Gujarat',
    specializations: ['Solar Plants', 'Transformers', 'Smart Streetlights'],
    licenseValidUntil: new Date('2029-06-30'),
    rating: 4.6,
  },
  {
    companyName: 'JalShakti Hydro Environmental Projects',
    registrationNumber: 'GJ-WRD-CL2-2021-088',
    contactPerson: 'Pradeep Jha',
    email: 'pradeep@jalshaktiprojects.com',
    phone: '+91 98250 33005',
    address: 'Ring Road Tower, Majura Gate, Surat, Gujarat',
    specializations: ['Water Treatment Plants', 'Underground Pipelines', 'Pumping Stations'],
    licenseValidUntil: new Date('2027-09-30'),
    rating: 4.5,
  },
];

module.exports = {
  demoUsers,
  departmentsData,
  contractorsData,
};
