/**
 * InfraTrack System Constants and Enums
 */

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  DEPARTMENT_ADMIN: 'DEPARTMENT_ADMIN',
  ENGINEER: 'ENGINEER',
  INSPECTOR: 'INSPECTOR',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  CONTRACTOR: 'CONTRACTOR',
  AUDITOR: 'AUDITOR',
};

const ASSET_CATEGORIES = {
  TRANSPORT: 'TRANSPORT',
  BUILDINGS: 'BUILDINGS',
  WATER: 'WATER',
  ENERGY: 'ENERGY',
  LAND: 'LAND',
};

const ASSET_TYPES = [
  'Road',
  'Bridge',
  'Culvert',
  'Streetlight',
  'Traffic Signal',
  'School',
  'Hospital',
  'Government Office',
  'Police Station',
  'Community Center',
  'Pipeline',
  'Water Tank',
  'Pump',
  'Drain',
  'Treatment Plant',
  'Transformer',
  'Solar Plant',
  'Generator',
  'Government Land',
  'Park',
  'Playground',
];

const ASSET_STATUS = {
  PLANNED: 'PLANNED',
  UNDER_CONSTRUCTION: 'UNDER_CONSTRUCTION',
  COMMISSIONED: 'COMMISSIONED',
  OPERATIONAL: 'OPERATIONAL',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  TEMPORARILY_CLOSED: 'TEMPORARILY_CLOSED',
  RETIRED: 'RETIRED',
  DECOMMISSIONED: 'DECOMMISSIONED',
};

const ASSET_CONDITION = {
  EXCELLENT: 'EXCELLENT',
  GOOD: 'GOOD',
  MODERATE: 'MODERATE',
  POOR: 'POOR',
  CRITICAL: 'CRITICAL',
};

const LIFECYCLE_EVENTS = {
  PROJECT_CREATED: 'PROJECT_CREATED',
  CONSTRUCTION_STARTED: 'CONSTRUCTION_STARTED',
  CONSTRUCTION_COMPLETED: 'CONSTRUCTION_COMPLETED',
  ASSET_CREATED: 'ASSET_CREATED',
  ASSET_COMMISSIONED: 'ASSET_COMMISSIONED',
  INSPECTION_COMPLETED: 'INSPECTION_COMPLETED',
  ISSUE_REPORTED: 'ISSUE_REPORTED',
  MAINTENANCE_RECOMMENDED: 'MAINTENANCE_RECOMMENDED',
  MAINTENANCE_STARTED: 'MAINTENANCE_STARTED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
  WORK_ORDER_CREATED: 'WORK_ORDER_CREATED',
  WORK_ORDER_ASSIGNED: 'WORK_ORDER_ASSIGNED',
  WORK_ORDER_STARTED: 'WORK_ORDER_STARTED',
  WORK_ORDER_COMPLETED: 'WORK_ORDER_COMPLETED',
  WORK_ORDER_VERIFIED: 'WORK_ORDER_VERIFIED',
  WORK_ORDER_CLOSED: 'WORK_ORDER_CLOSED',
  ASSET_TRANSFERRED: 'ASSET_TRANSFERRED',
  ASSET_RETIRED: 'ASSET_RETIRED',
};

const WORK_ORDER_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
  URGENT: 'URGENT',
};

const WORK_ORDER_STATUS = {
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  VERIFIED: 'VERIFIED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
  DRAFT: 'DRAFT',
};

const ISSUE_STATUS = {
  REPORTED: 'REPORTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  VERIFIED: 'VERIFIED',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
};

const ISSUE_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const MAINTENANCE_STATUS = {
  PLANNED: 'PLANNED',
  APPROVED: 'APPROVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const MAINTENANCE_TYPE = {
  ROUTINE: 'ROUTINE',
  PREVENTIVE: 'PREVENTIVE',
  CORRECTIVE: 'CORRECTIVE',
  EMERGENCY: 'EMERGENCY',
};

const PROJECT_STATUS = {
  PROPOSED: 'PROPOSED',
  APPROVED: 'APPROVED',
  UNDER_CONSTRUCTION: 'UNDER_CONSTRUCTION',
  COMPLETED: 'COMPLETED',
  COMMISSIONED: 'COMMISSIONED',
  CANCELLED: 'CANCELLED',
};

const PROJECT_MILESTONES = [
  'Planning',
  'Approval',
  'Construction',
  'Inspection',
  'Completion',
  'Commissioning',
];

const DOCUMENT_TYPES = [
  'Construction Certificate',
  'Completion Certificate',
  'Inspection Report',
  'Maintenance Report',
  'Invoice',
  'Drawing',
  'Contract',
  'Photograph',
  'Other',
];

const FINANCIAL_RECORD_TYPES = {
  ACQUISITION: 'ACQUISITION',
  CONSTRUCTION: 'CONSTRUCTION',
  MAINTENANCE: 'MAINTENANCE',
  REPAIR: 'REPAIR',
  OPERATION: 'OPERATION',
  DISPOSAL: 'DISPOSAL',
};

const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  APPROVE: 'APPROVE',
  ASSIGN: 'ASSIGN',
  TRANSFER: 'TRANSFER',
  INSPECT: 'INSPECT',
  MAINTAIN: 'MAINTAIN',
  COMPLETE: 'COMPLETE',
  VERIFY: 'VERIFY',
  RETIRE: 'RETIRE',
};

module.exports = {
  ROLES,
  ASSET_CATEGORIES,
  ASSET_TYPES,
  ASSET_STATUS,
  ASSET_CONDITION,
  LIFECYCLE_EVENTS,
  WORK_ORDER_PRIORITY,
  WORK_ORDER_STATUS,
  ISSUE_STATUS,
  ISSUE_SEVERITY,
  MAINTENANCE_STATUS,
  MAINTENANCE_TYPE,
  PROJECT_STATUS,
  PROJECT_MILESTONES,
  DOCUMENT_TYPES,
  FINANCIAL_RECORD_TYPES,
  AUDIT_ACTIONS,
};
